name: "Destroy Infrastructure"

on:
  workflow_dispatch:
    inputs:
      cluster_path:
        description: "repository path representing the cluster"
        type: string
        default: "westeurope/non-prod/k01"
      apply:
        description: "apply directly the changes"
        type: choice
        options:
          - yes
          - no
        default: no

concurrency:
  group: ${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ inputs.apply == 'yes' }}
    name: "Terragrunt RunAll Destroy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: ./.github/actions/bootstrap-runner
        with:
          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply
        shell: bash
        run: |
          terragrunt run-all destroy --terragrunt-non-interactive
